const products = [
    {
      id: 1,
      imageUrl: '../Assets/p1.png',
      name: 'Product 1',
      price: 19.99,
      category: 'Electronics',
      description: 'A high-quality product with amazing features.',
      rating: 4.5,
      reviews: 23,
      tags: ['new', 'featured'],
      colorOptions: ['red', 'blue'],
    },
    {
      id: 2,
      imageUrl: '../Assets/p1.png',
      name: 'Product 2',
      price: 29.95,
      category: 'Clothing',
      description: 'A stylish and comfortable piece of clothing.',
      rating: 4.2,
      reviews: 117,
      tags: ['summer', 'sale'],
      colorOptions: ['black', 'white', 'green'],
    },
    {
      id: 3,
      imageUrl: '../Assets/p1.png',
      name: 'Product 3',
      price: 49.99,
      category: 'Homeware',
      description: 'A useful and practical item for your home.',
      rating: 4.8,
      reviews: 32,
      tags: ['kitchen', 'organization'],
      colorOptions: ['gray', 'white'],
    },
    {
      id: 4,
      imageUrl: '../Assets/p1.png',
      name: 'Product 4',
      price: 15.99,
      category: 'Electronics',
      description: 'A budget-friendly product with great value.',
      rating: 4.0,
      reviews: 98,
      tags: ['wireless', 'headphones'],
      colorOptions: ['black', 'blue'],
    },
    {
      id: 5,
      imageUrl: '../Assets/p1.png',
      name: 'Product 5',
      price: 34.50,
      category: 'Sports',
      description: 'A product that helps you stay active and healthy.',
      rating: 4.7,
      reviews: 121,
      tags: ['fitness', 'yoga'],
      colorOptions: ['pink', 'purple'],
    },
    {
      id: 6,
      imageUrl: '../Assets/p1.png',
      name: 'Product 6',
      price: 79.99,
      category: 'Beauty',
      description: 'A product that enhances your natural beauty.',
      rating: 4.9,
      reviews: 412,
      tags: ['skincare', 'moisturizer'],
      colorOptions: ['none'], // No color options for this product
    },
    {
      id: 7,
      imageUrl: '../Assets/p1.png',
      name: 'Product 7',
      price: 24.99,
      category: 'Toys',
      description: 'A fun and engaging toy for children.',
      rating: 4.3,
      reviews: 78,
      tags: ['educational', 'building blocks'],
      colorOptions: ['multicolor'],
    },
    {
      id: 8,
      imageUrl: '../Assets/p1.png',
      name: 'Product 8',
      price: 9.99,
      category: 'Books',
      description: 'A captivating book that will keep you turning the pages.',
      rating: 5.0,
      reviews: 842,
      tags: ['bestseller', 'mystery'],
    },
  ];

  export default products